/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  ctf_Sidebar:[{type: 'autogenerated',dirName: 'CTF'}],
  LD_Sidebar:[{type: 'autogenerated' ,dirName: '蓝队'}],
  BC_Sidebar:[{type: 'autogenerated' ,dirName: '靶场'}],
  ZJ_Sidebar:[{type: 'autogenerated' ,dirName: '杂记'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
